### ISSUE TITLE
Schedule meeting with client

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#1]
Offline meeting to discuss requirements for project - Preferably on the second week

**Comment by afiqdanialll** [comment]
Task details: To schedule and organise a meet with client on 2nd or 3rd week

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**Able to better understand the needs and requirements of the client and also uncover more requirements that may not have been informed prior to the meet.**

Success/completion criteria: How do we know we completed the goal successfully
**Upon completion of the meeting**

Allocated time: 1 week 

Start date: 29/8/23

End date: 11/9/23

Task owner: Afiq

Task status: Completed

Task priority: HIGH

**Comment by afiqdanialll** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
**Scheduled an interview with client and met up successfully**

Has this work been committed to the repo?
**Yes**

How does the work affect the completion deadline.
**Allows us to understand further the user's requirements allowing us to move forward with project**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No**

Start and end date of the work done for this comment.
**5/9 - 11/9**
