### ISSUE TITLE
Design Use Case Diagram

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#10]
Task details: Explain what the task is about here
**To create a Use Case Diagram**

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**Enables readers to see an overview of the functions and requirements**

Success/completion criteria: How do we know we completed the goal successfully
**Completion involves a well-structured Use Case Diagram that accurately represents the system's functional requirements, actors, and use cases.**

Allocated time: 4 days

Start date: 16/9/23

End date: 19/9/23

Task owner: Jun Wei

Task status: Completed

Task priority: **HIGH**

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Design the use case diagram using the functional requirement.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
16/9 - 19/9
