### ISSUE TITLE
Validate sequence diagram

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#105]
Task Details: Validate the details of sequence diagram matches with use case diagrams and use case descriptions

Task Goals: Ensures that the sequence diagram tallies with the use cases 

Success/Completion Criteria: Successful completion means that the sequence diagram accurately captures the sequence of events and actors described in the use cases.

Allocated time: 3 days

Start date: 18/10/23

End date: 21/10/23

Task owner:  Rui Zhe

Task status: Backlog

Task priority:

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Ensure that the sequence diagram is done correctly and accurately

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
18/10 - 21/10
