### ISSUE TITLE
Update Software Requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#106]
Task details: Update requirements as per feedback from M1 submission

Task goals: To ensure that requirements meet the standards set by profs

Success/completion criteria: Updated requirements follow requirements set by professors

Allocated time: 4 days

Start date: 24/9/23

End date: 27/9/23

Task owner: Ruizhe

Task status: Completed

Task priority: High

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Software requirements have been updated.

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
24/9 - 27/9
