### ISSUE TITLE
Update Use Cases

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#107]
Task details: To update the use cases based off feedback from M1 submission

Task goals: To update the use case descriptors and use case diagram to meet the feedback from m1 submisison

Success/completion criteria: Ucse case diagrams and use case descriptors are updated to meet the feedback from m1 submission

Allocated time: 5 days

Start date: 28/9/23

End date: 1/10/23

Task owner: Junwei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
Edited the use case to better suit the requirement of our project and as per the feedback gotten from M1

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
28/9 - 1/10
