### ISSUE TITLE
Update Use Case Diagram

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#108]
Task details: To update the use cases diagram

Task goals: To update the use case diagram based off the m1 submissions feedback

Success/completion criteria: Use case diagram updated to better capture the requirements listed 

Allocated time: 5 days

Start date: 28/9/23

End date: 1/10/23

Task owner: Junwei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
Added in the external database and ensure the name tally with the use case

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
28/9 - 1/10
