### ISSUE TITLE
Update Use Case Descriptors

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#109]
Task details: To update the use cases descriptors

Task goals: To update the use case descriptors based off the m1 submissions feedback

Success/completion criteria: Use case descriptors updated to better capture the requirements listed

Allocated time: 5 days

Start date: 28/9/23

End date: 1/10/23

Task owner: Junwei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
Adjust the use case along with the description to better suit our project with its requirement

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
28/9 - 1/10
