### ISSUE TITLE
Define Use Case Descriptions

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#11]
Task details: Explain what the task is about here
**Write detailed descriptions for each use case on how specific functionalities or features, within a software system interact with users, including preconditions, postconditions, and main flow.**

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**Provide in-depth documentation for each use case, ensuring that developers have a clear understanding of how each function should work.**

Success/completion criteria: How do we know we completed the goal successfully
**Successful completion means that each use case has a detailed description that is consistent with the Use Case Diagram and free from ambiguities.**

Allocated time: **4 Days**

Start date: **16/9/23**

End date: **19/9/23**

Task owner: **Jun Wei**

Task status:**Completed**

Task priority: **High**

**Comment by juunweiii** [comment]
Task Comments: 
Describe the work done in detail.
**Explain more in detail on the use cases that we have come out and allowing user to understand how the process going to be like**

Has this work been committed to the repo?
**No.**

How does the work affect the completion deadline.
**Allows the continuation of work ensuring deadline is met.**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No.**

Start and end date of the work done for this comment.
**16/9 - 19/9**
