### ISSUE TITLE
Update Gantt Chart

### ISSUE THREAD

**Issue by juunweiii** [afiqdanialll/INF2001-P8-4#110]
Task details: Update gantt chart as the project progress to ensure it stay relevant and in track with the timeline.

Task goals: To ensure everyone is on the same track when the project progress.

Success/completion criteria: Updated gantt chart and ensure that the chart remains accurate and aligns with the project's current status

Allocated time: 4 days

Start date: 28/9/23

End date: 01/10/23

Task owner: JiaYi

Task status: Completed

Task priority: High

**Comment by symphonyalpha** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Updated gantt chart and ensure that the chart remains accurate and aligns with the project's current status

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
provides team with a clear timeline of when certain tasks should be completed by to ensure smooth closure of project

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
28/9/23 - 1/10/23
