### ISSUE TITLE
Implement Detailed Design

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#113]
Task details: Implement detailed design on existing class diagram

Task goals: Use existing design patterns to 'upgrade' existing class diagram

Success/completion criteria: Proper implementation of detailed design

Allocated time: 4 days

Start date: 29/10/23

End date: 1/11/23

Task owner: Jia Yi

Task status: Backlog

Task priority: High

**Comment by symphonyalpha** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Implement detailed design on existing class diagram

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Can move on with starting other tasks once this is done

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
29/10/23-1/11/23
