### ISSUE TITLE
Prototype for IT Administrator use cases

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#116]
Task details: Explain what the task is about here

Task goals: Explain what the end result of the task is/what the task is supposed to achieve

Success/completion criteria: How do we know we completed the goal successfully

Allocated time: 4 Days

Start date: 4/11/23

End date: 7/11/23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: NIL

Describe the work done in detail. **Created the screens relating to use case A1 and verified that it meets the requirements needed for this use case.**

Has this work been committed to the repo? **yes**

How does the work affect the completion deadline. **Required for report writing and video demo.**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details. **no**

Start and end date of the work done for this comment. 4-7 Nov 2023
