### ISSUE TITLE
Prototype for Manager use case

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#123]
Task details: Explain what the task is about here

Task goals: Explain what the end result of the task is/what the task is supposed to achieve

Success/completion criteria: How do we know we completed the goal successfully

Allocated time: 5 days

Start date: 11 Nov 23

End date: 15 Nov 23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: **NIL**

Describe the work done in detail. **Oversaw the creation of all screens relating to the Manager use cases**

Has this work been committed to the repo? **yes**

How does the work affect the completion deadline. **Required for report writing and video demo**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details. **No**

Start and end date of the work done for this comment. **11-15 Nov 2023**
