### ISSUE TITLE
Blackbox Testing

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#129]
Task details: Overall tracker for blackbox tesing 

Task goals: To track the overall time given for the entire blackbox testing phase

Success/completion criteria: Time tracked properly for this task

Allocated time: 6 days

Start date: 15/11/23

End date: 20/11/23

Task owner: Jia Yi

Task status: Backlog

Task priority: High

**Comment by symphonyalpha** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
completed all the test plans for the selected use case

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Can move on with starting other tasks once this is done

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
15/11/23-20/11/23
