### ISSUE TITLE
White Box Testing

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#134]
Task details: Testing the internal structure and working of an use case

Task goals: Ensure the internal logic, code paths of the use case is functioning correctly

Success/completion criteria: Ensure the testing test all the test case

Allocated time: 6 Days

Start date: 20/11

End date: 25/11

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Created the white box testing and identify the method is used.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
20/11 - 25/11
