### ISSUE TITLE
Design control flow graph

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#136]
Task details: Design a control flow graph to provide visualisation of the flow of control between various statement and decision point.

Task goals: Help stakeholder understand the program structure with the aid of visual graph.

Success/completion criteria: Successfully identify all the all the decision point and code flow.

Allocated time: 2 Days

Start date: 22/11

End date: 23/11

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create a pseudocode and the graph for the code.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
22/11 - 23/11
