### ISSUE TITLE
Determine test cases for basic paths

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#139]
Task details: Using the Control Flow Graph and identify all the possible path 

Task goals: Create a set of test cases that cover all the essential path through the use case. 

Success/completion criteria: Successfully coming out with all the test case to cover the basic path.

Allocated time: 2 Days

Start date: 24/11

End date: 25/11

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Identifying all the test case for the basic path and documenting it down.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
24/11 - 25/11
