### ISSUE TITLE
Define functional requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#14]
Task title ID: 1.4.2

Task Details: Involves gathering and documenting all functional requirements, including those related to the user interface

Task Goals: The goal is to clearly define and describe what the software should do to meet user needs and expectations.

Success/Completion Criteria: Produce a comprehensive list of functional requirements that are well-documented, unambiguous and aligns with client's expectations. 

Allocated time: Approx 2 weeks 

Start date: 9/9/23

End date: 16/9/23

Task owner: Ruizhe

Task status: To-Do 

Task priority: High

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Gather all the functional requirements, including those from the meeting with the client

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Should help ensure everyone is on track or aware of tasks that need doing

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
9/9/23-16/9/23
