### ISSUE TITLE
Define non-functional requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#15]
Task title ID: 1.4.3

Task Details: Identify and document the non-functional aspects of the software, such as performance, safety and security requirements
In this task, you'll identify and document the non-functional aspects that the software must possess, such as performance, security, and usability.

Task Goals: Ensure that the system functions correctly

Success/Completion Criteria: Successful completion means having a clear and comprehensive list of non-functional requirements that are measurable and achievable.

Allocated time: Approx 2 weeks

Start date: 9/9/23

End date: 16/9/23

Task owner: Ruizhe

Task status: To-do

Task priority: High priority

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Research more on the non-functional requirements, including performance requirements, security requirements and any other requirements

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Should help ensure everyone is on track or aware of tasks that need doing

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
9/9/23-16/9/23
