### ISSUE TITLE
Define basic use cases

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#16]
Task Details: Identify and outline the fundamental actions or interactions that users can perform within the software.

Task Goals: To specify the core functionalities and user interactions.

Success/Completion Criteria: Successful completion involves a list of well-defined basic use cases that cover the essential user interactions with the system.

Allocated time: 4 days

Start date: 16/9/23

End date: 19/9/23

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Identifying and coming out with the use cases

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
16/9 - 19/9
