### ISSUE TITLE
Define actors

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#17]
Task Details: Identify and describe the entities (users or external systems) that interact with the system.

Task Goals: To define who or what interacts with the software and understand their roles.

Success/Completion Criteria: Successful completion includes a clear list of actors and their roles and responsibilities within the system.

Allocated time: 4 day

Start date: 16/9/23

End date: 19/9/23

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Identifying the user that will be using/interacting with the systems

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
16/9 - 19/9
