### ISSUE TITLE
Software Estimation

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#18]
Task Details: Estimate the size and effort required for the project.

Task Goals: The goal is to determine the resources and schedule needed for the project.

Success/Completion Criteria: Successful completion involves accurate size and effort estimates that align with project constraints and objectives.

Allocated time: 4 days

Start date: 20/9/23

End date: 23/9/23

Task owner: Person that is in-charge of this task. In-charge doesn't mean only person doing. Please update assignee when creating a task.

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
20/9/23 - 23/9/23
