### ISSUE TITLE
Conduct Project Size Estimation

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#19]
Task Details: Assess the quantify the size and scope of the software project using use cases

Task Goals: The goal is to establish a clear understanding of the project's scale and size, which is crucial for resource planning and project management.

Success/Completion Criteria: Successful completion means that the size of the project has been accurately estimated using a recognized and appropriate metric, providing a reliable measure of the project's scope.

Allocated time: 4 days

Start date: 20/9/23

End date: 23/9/23

Task owner: Afiq

Task status: To-do

Task priority: High

**Comment by afiqdanialll** [comment]
Task Comments: Completed

Describe the work done in detail. Assess the quantify the size and scope of the software project using use cases and established the project size estimation.

Has this work been committed to the repo? No

How does the work affect the completion deadline. Required in meeting deadline

Are there any changes to the success or completion criteria of the task? If yes, please describe the details. No

Start and end date of the work done for this comment. 20-23/9/23
