### ISSUE TITLE
Conduct Project Effort Estimation

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#20]
Task Details: Determine the resources and effort required to complete the software project. This includes identifying the personnel, time, tools, and other resources needed for successful project execution.

Task Goals: The goal is to ensure that you have a clear understanding of the resource requirements and effort involved in delivering the project.

Success/Completion Criteria: Successful completion involves the following:
- Accurately estimating the effort required to complete the project.
- Identifying the necessary personnel with the appropriate skill sets.
- Determining the tools and technology stack needed for development.
- Aligning the effort estimation with the project's scope and objectives.

Allocated time: 4 Days

Start date: 20/9/23

End date: 23/9/23

Task owner: Person that is in-charge of this task. In-charge doesn't mean only person doing. Please update assignee when creating a task.

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
20/9/23 - 23/9/23
