### ISSUE TITLE
Design System Diagram

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#32]
Task details: Explain what the task is about here
**To design a system diagram**

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**To be able to come up with a system diagram that shows the connectivity between the front end, backend and server.**

Success/completion criteria: How do we know we completed the goal successfully
**When the diagram is completed and everyone agrees with the design**

Allocated time: 
**2 days**

Start date: 
**19/9/23**

End date:
**21/9/23**

Task owner: Person that is in-charge of this task. In-charge doesn't mean only person doing. Please update assignee when creating a task.

Task status: 
**Ongoing**

Task priority:
**High**

**Comment by ivanlsy** [comment]
ok

**Comment by ivanlsy** [comment]
Design System Diagram (System Architecture Design) done.

**Comment by ivanlsy** [comment]
Task Comments: 
Completed the Design System Diagram. 
Clarity on how the System works.

Has this work been committed to the repo?
No

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start and end date of the work done for this comment.(DDMMYYYY - DDMMYYYY)
19092023 - 23092023
