### ISSUE TITLE
Background Literature Review

### ISSUE THREAD

**Issue by ivanlsy** [afiqdanialll/INF2001-P8-4#33]
Task details: **Doing a background research on the domain of the project such as understand how does the company operation and the daily routine. And any related article on the issue that is causing the rise of this project.**

Task goals: **Everyone understand the problem we are tackling and have a basic background understand of the project.**

Success/completion criteria: **90% of the doubt we previous have are all resolve after the intensive research.**

Allocated time: **2 weeks**

Start date: **29/8/23**

End date: **11/9/23**

Task owner: **Ivan**

Task status: **Completed**

Task priority: **High**

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
**Everyone had a intensive research of the topic of the project and understand the objective we trying to achieve here.** 

Has this work been committed to the repo?
**No.**

How does the work affect the completion deadline.
**Allows the continuation of work ensuring deadline is met.**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No.**

Start and end date of the work done for this comment.
**29/8 - 11/9**
