### ISSUE TITLE
Define performance requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#40]
Task details: This task focuses on specifying performance-related requirements, such as response times, throughput, and system resource usage.

Task goals:  To ensure that the system performs efficiently and meets performance expectations.

Success/completion criteria: 
- Clearly defined performance metrics and benchmarks.
- Performance requirements documented for different system components.
- Acceptance criteria for performance testing.

Allocated time: 1 week

Start date: 9/9/23

End date: 16/9/23

Task owner: Ruizhe

Task status: To-do

Task priority: High

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Gathering of non-functional performance requirements, including those from the meeting with the client

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Should help ensure everyone is on track or aware of tasks that need doing

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
9/9/23-16/9/23
