### ISSUE TITLE
Define safety requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#41]
Task details: This task involves defining safety-related requirements, particularly if the application has safety-critical aspects.

Task goals: To ensure that the application operates safely and mitigates potential risks.

Success/completion criteria:    

- Clear safety requirements documented, including any regulatory or compliance standards.
- Identification of potential safety hazards and mitigation strategies.
- Documentation of safety testing and validation procedures.

Allocated time: 1 week

Start date: 9/9/23

End date: 16/9/23

Task owner: Ruizhe

Task status: To-do

Task priority: High

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Gather all the non-functional safety requirements, including those from the meeting with the client

Has this work been committed to the repo?
Not applicable

How does the work affect the completion deadline.
Should help ensure everyone is on track or aware of tasks that need doing

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
9/9/23-16/9/23
