### ISSUE TITLE
Estimate Use Case Points (UCP)

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#42]
Task details:  This task involves estimating the size of the project using the Use Case Points (UCP) method, which quantifies the functional requirements.

Task goals: To determine the size of the project in terms of functionality and scope.

Success/completion criteria:     

- Calculation of UCP for each use case.
- Total UCP for the entire project.
- Documentation of assumptions and inputs used in UCP estimation.

Allocated time: 4 days

Start date: 20/9/23

End date: 23/9/23

Task owner: 

Task status: To-do

Task priority: High

**Comment by afiqdanialll** [comment]
Task Comments: Completed.

Describe the work done in detail.  
Calculated UCP for each use case., total UCP for the entire project and documentation of assumptions and inputs used in UCP estimation.

Has this work been committed to the repo? No

How does the work affect the completion deadline. Required as part of deadline

Are there any changes to the success or completion criteria of the task? If yes, please describe the details. No

Start and end date of the work done for this comment. 20-23/9/23
