### ISSUE TITLE
Estimate Effort in Person-Months using COCOMO

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#43]
Task details: This task entails estimating the effort required to complete the project in person-months using the COCOMO (Constructive Cost Model) method.

Task goals: To predict the effort and resources needed for project execution.

Success/completion criteria:

- Estimation of effort in person-months.
- Detailed breakdown of effort estimation for various project phases.
- Documentation of COCOMO model parameters and assumptions.

Allocated time: 4 days

Start date: 20/9/23

End date: 23/9/23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
20/9/23 - 23/9/23
