### ISSUE TITLE
Define User Interface Requirements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#44]
Task details: This task involves specifying the requirements related to the user interface (UI) design of the application.

Task goals: To ensure that the user interface meets user expectations and provides a positive user experience.

Success/completion criteria: A comprehensive list of UI elements and features required.

Allocated time: 4 days

Start date: 20/9/23

End date: 23/9/23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
We gathered and documented the comprehensive user interface requirements for our application

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
20/9 - 23/9
