### ISSUE TITLE
Define Product Scope

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#48]
Task details: Explain what the task is about here
**To Provide a short description of the software scope, boundaries, and its purpose, including relevant benefits, objectives, and goals.**

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**Provides better understanding  of the software scope, boundaries, and its purpose, including relevant benefits, objectives, and goals.**

Success/completion criteria: How do we know we completed the goal successfully
 **1-2 paragraphs describing the scope of the product. Make sure to describe the benefits associated with the product.**

Allocated time: Approx 5 days

Start date: 16/9/23

End date: 20/9/23

Task owner: Person that is in-charge of this task. In-charge doesn't mean only person doing. Please update assignee when creating a task.
**Zhi Yin**

Task status: **Completed**

Task priority: **High**

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
We define it to ensure the product scope document the outlines of the features, functionalities, and limitations of the project and also ensuring alignment with project goals and expectations.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
16/9 - 20/9
