### ISSUE TITLE
Define Product Overview

### ISSUE THREAD

**Issue by afiqdanialll** [afiqdanialll/INF2001-P8-4#49]
Task details: Explain what the task is about here
**To describe the context and origin of the product being specified in this document.**

Task goals: Explain what the end result of the task is/what the task is supposed to achieve
**Provides better understanding of context and origin of the product being specified in this document.**

Success/completion criteria: How do we know we completed the goal successfully
 **1-2 paragraphs describing the overview of the product.**

Allocated time: Approx 5 days

Start date: 16/9/23

End date: 20/9/23

Task owner: Person that is in-charge of this task. In-charge doesn't mean only person doing. Please update assignee when creating a task.
**Zhi Yin**

Task status: **Completed**

Task priority: **High**

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
Explain more in detail of what is our product and how our product fits into the need of client

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
16/9 - 20/9
