### ISSUE TITLE
Design Class Diagram

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#50]
Task Details: Create a class diagram to represent the system's structure.

Task Goals: To visually illustrate the classes and their relationships within the system.

Success/Completion Criteria: A complete class diagram that accurately depicts system classes and their attributes, 
methods, and relationships.

Allocated Time: 1/10/23 to 10/10/23
Start Date: 1/10/23

End Date: 10/10/23

Task Owner: Ivan

Task status: Backlog

Task Priority:

**Comment by ivanlsy** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Design Class Diagram

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
1/10/23 to 10/10/23
