### ISSUE TITLE
Establish relationships

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#55]
Task Details: Create relationships between the identified classes in the class diagram. These relationships define how classes interact with each other.

Task Goals: The goal is to establish a clear understanding of how classes are connected within the system.

Success/Completion Criteria: Successful completion involves defining associations and relationships between classes, accurately reflecting the system's structure.

Allocated time: 8/10/23 to 10/10/23

Start date: 8/10/23

End date: 10/10/23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
8/10/23 - 10/10/23
