### ISSUE TITLE
Design Sequence Diagram

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#59]
Task Details: Create sequence diagrams to illustrate the interactions and message flow between actors and objects in the system.

Task Goals: The goal is to visualize the dynamic behavior of the system during specific processes or scenarios.

Success/Completion Criteria: Successful completion means having sequence diagrams that accurately depict message flow and interactions. 

Allocated time: 10 days

Start date: 11/10/23

End date: 21/10/23

Task owner: Zhi Yin, Afiq

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
11/10/23 - 21/10/23
