### ISSUE TITLE
Define lifelines elements

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#61]
Task Details: Define the lifelines for each actor and object in the sequence diagrams. Lifelines represent the existence and involvement of these entities.

Task Goals: The goal is to specify the duration and participation of each actor and object in the sequences.

Success/Completion Criteria: Successful completion involves defining lifelines for all actors and objects. 

Allocated time: 3 days

Start date: 11/10/23

End date: 14/10/23

Task owner: Zhi Yin

Task status: Completed

Task priority: High

**Comment by zhiyinang** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Create the necessary communication channels

Has this work been committed to the repo?
not applicable

How does the work affect the completion deadline.
no effect

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
no changes

Start and end date of the work done for this comment.
11/10/23 - 14/10/23
