### ISSUE TITLE
Capture message flow

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#62]
Task Details: Capture and document the flow of messages between actors and objects in the sequence diagrams.

Task Goals: The task aims to illustrate how information and actions are exchanged during system processes.

Success/Completion Criteria: Successful completion includes a clear depiction of message flow within the sequence diagrams. 

Allocated time: 2 days

Start date: 15/10/23

End date: 17/10/23

Task owner: Afiq

Task status: Backlog

Task priority:

**Comment by afiqdanialll** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
**To depict the communication and interaction between objects or components in a system.  Capturing the message flow in a sequence diagram involves showing the chronological order of messages sent between the different objects over time.**

Has this work been committed to the repo?
**Yes**

How does the work affect the completion deadline.
**This aids in the completion of the sequence diagram and as a whole, the M2 submission*

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No**

Start and end date of the work done for this comment.
**15 - 17 Oct 2023**

**Comment by afiqdanialll** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
**To depict the communication and interaction between objects or components in a system.  Capturing the message flow in a sequence diagram involves showing the chronological order of messages sent between the different objects over time.**

Has this work been committed to the repo?
**Yes**

How does the work affect the completion deadline.
**This aids in the completion of the sequence diagram and as a whole, the M2 submission*

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No**

Start and end date of the work done for this comment.
**15 - 17 Oct 2023**
