### ISSUE TITLE
Add alternative flow (if required)

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#65]
Task Details: Annotate the timing aspects in the sequence diagrams to indicate the duration of each step or message.

Task Goals: The task aims to provide a sense of timing and duration for the interactions.

Success/Completion Criteria: Successful completion includes clear annotations of timing in the sequence diagrams. 

Allocated time: 2 days

Start date: 15/10/23

End date: 17/10/23

Task owner: Afiq

Task status: Backlog

Task priority:

**Comment by afiqdanialll** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
**To identify the path of execution that diverges from the main or primary flow of actions in response to the various possible outcomes and flow from the use case descriptions. Then to draw the alternative flow in the sequence diagram.**

Has this work been committed to the repo?
**Yes**

How does the work affect the completion deadline.
**This aids in the completion of the sequence diagram and as a whole, the M2 submission*

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**No**

Start and end date of the work done for this comment.
**15 - 17 Oct 2023**
