### ISSUE TITLE
Design Component Diagram

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#66]
Task Details: Create a component diagram that illustrates the high-level components and their relationships within the system.

Task Goals: The goal is to provide an overview of the system's structure and interactions at a component level.

Success/Completion Criteria: Successful completion involves a component diagram that accurately represents the system's architecture. 

Allocated time: 8 days

Start date: 21/10/23

End date: 28/10/23

Task owner: Ruizhe

Task status: Backlog

Task priority:

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Component Diagram has been designed and created accurately

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
21/10 - 28/10
