### ISSUE TITLE
Identify Components

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#67]
Task Details: Identify and list the components within the system that will be represented in the component diagram.

Task Goals: The task aims to define the major components that constitute the system.

Success/Completion Criteria: Successful completion includes a list of identified components.

Allocated time: 3 days

Start date: 21/10/23

End date: 24/10/23

Task owner: Jun Wei

Task status: Completed

Task priority: High

**Comment by juunweiii** [comment]
Task Comments:
Describe the work done in detail.
Identifying the component  in our project to ensure our project work flow and clear.

Has this work been committed to the repo?
No.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
21/10 - 24/10
