### ISSUE TITLE
Identify ports and delegates

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#69]
Task Details: Determine the ports and delegates necessary for component communication within the system architecture.

Task Goals: Define how components within the system will interact with each other through ports and delegates.

Success/Completion Criteria: Successful completion includes documentation that clearly outlines the identified ports and delegates, their roles, and the component interactions they enable within the component diagram.

Allocated time: 4 day

Start date: 25/10/23

End date: 28/10/23

Task owner: Rui Zhe

Task status: Backlog

Task priority:

**Comment by Ruizheee** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Identified all necessary ports and delegates in the component diagram

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
Allows the continuation of work ensuring deadline is met.

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No.

Start and end date of the work done for this comment.
25/10 - 28/10
