### ISSUE TITLE
Backup and disaster recover setup

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#74]
Task Details: Implement backup and disaster recovery mechanisms to safeguard application data and functionality.

Task Goals: To protect against data loss and ensure business continuity in case of unforeseen events.

Success/Completion Criteria: Successful completion means the implementation of effective backup and disaster recovery solutions. 

Allocated time: 2 days

Start date: 19/11/23

End date: 20/11/23

Task owner: Ivan

Task status: Backlog 

Task priority:

**Comment by ivanlsy** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Implementation of effective back and disaster recovery solutions.

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
Sets a precedence of team expectations and progress

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
19/11 - 20/11
