### ISSUE TITLE
Implement user permissions

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#89]
Task Details: Implement user permission management to control access and actions within the application.

Task Goals: To ensure proper security and user role management.

Success/Completion Criteria: Successful completion involves user permissions that restrict access as intended. 

Allocated time: 3 days

Start date: 5/11/23

End date: 7/11/23

Task owner: Ivan

Task status: Backlog

Task priority:

**Comment by ivanlsy** [comment]
Task Comments: User has restricted access based on type of user account.

Describe the work done in detail.
Restrict user access

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
Sets a precedence of team expectations and progress

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
5/11 - 7/11
