### ISSUE TITLE
Conduct testing

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#95]
Task Details: Execute thorough testing procedures to validate the application's functionality.

Task Goals: Ensure comprehensive testing of the application, covering white-box and black-box testing as well as integration and user acceptance testing.

Success/Completion Criteria: Conduct thorough testing, address issues promptly, and maintain application quality and functionality within defined timelines.

Allocated time: 5 days

Start date: 10/11/23

End date: 14/11/23

Task owner: Ivan

Task status: Backlog

Task priority:

**Comment by ivanlsy** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Tested the system for issues, its quality and functionality.

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
Sets a precedence of team expectations and progress

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
10/11 - 14/11
