### ISSUE TITLE
Perform white-box unit testing

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#96]
Task Details: Execute white-box unit testing to assess the functionality of individual components or modules.

Task Goals: To identify and address issues at the unit level.

Success/Completion Criteria: Successful completion means the execution of effective white-box unit tests. 

Allocated time: 4 days

Start date: 10/11/23

End date: 13/11/23

Task owner: Ivan

Task status: Backlog

Task priority:

**Comment by ivanlsy** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail.
Completed necessary white-box testing.

Has this work been committed to the repo?
Yes

How does the work affect the completion deadline.
Sets a precedence of team expectations and progress

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
No

Start and end date of the work done for this comment.
10/11 - 13/11
